name: Build and Deploy to deploy branch

on:
  workflow_dispatch:  
  pull_request:
    types: [closed]   
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push to deploy
    env:
      PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  

      - name: Push to deploy branch
        uses: s0/git-publish-subdir-action@v2
        env:
          REPO: self
          BRANCH: build            
          FOLDER: dist               
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Deploy: ({sha}) {msg}"